version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL}
      - VITE_AUTH_URL=${VITE_AUTH_URL}
    command: pnpm run dev
    depends_on:
      - socket-server
      - auth-server

  socket-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${SOCKET_PORT}:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${SOCKET_PORT}
    command: pnpm run start

  auth-server:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "${AUTH_PORT}:3001"
    volumes:
      - ./backend/app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${AUTH_PORT}
    command: pnpm run start
